In [1]:
import pandas as pd

In [2]:
hfi = pd.read_csv("edhec-hedgefundindices.csv",
                    sep = ';',
                    header=0, index_col=0, parse_dates=True, dayfirst=True)

In [3]:
hfi.head()

,Convertible Arbitrage,CTA Global,Distressed Securities,Emerging Markets,Equity Market Neutral,Event Driven,Fixed Income Arbitrage,Global Macro,Long/Short Equity,Merger Arbitrage,Relative Value,Short Selling,Funds Of Funds
date,,,,,,,,,,,,,
1997-01-31,1.19%,3.93%,1.78%,7.91%,1.89%,2.13%,1.91%,5.73%,2.81%,1.50%,1.80%,-1.66%,3.17%
1997-02-28,1.23%,2.98%,1.22%,5.25%,1.01%,0.84%,1.22%,1.75%,-0.06%,0.34%,1.18%,4.26%,1.06%
1997-03-31,0.78%,-0.21%,-0.12%,-1.20%,0.16%,-0.23%,1.09%,-1.19%,-0.84%,0.60%,0.10%,7.78%,-0.77%
1997-04-30,0.86%,-1.70%,0.30%,1.19%,1.19%,-0.05%,1.30%,1.72%,0.84%,-0.01%,1.22%,-1.29%,0.09%
1997-05-31,1.56%,-0.15%,2.33%,3.15%,1.89%,3.46%,1.18%,1.08%,3.94%,1.97%,1.73%,-7.37%,2.75%

In [5]:
hfi.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 294 entries, 1997-01-31 to 2021-06-30
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Convertible Arbitrage   294 non-null    object
 1   CTA Global              294 non-null    object
 2   Distressed Securities   294 non-null    object
 3   Emerging Markets        294 non-null    object
 4   Equity Market Neutral   294 non-null    object
 5   Event Driven            294 non-null    object
 6   Fixed Income Arbitrage  294 non-null    object
 7   Global Macro            294 non-null    object
 8   Long/Short Equity       294 non-null    object
 9   Merger Arbitrage        294 non-null    object
 10  Relative Value          294 non-null    object
 11  Short Selling           287 non-null    object
 12  Funds Of Funds          294 non-null    object
dtypes: object(13)
memory usage: 32.2+ KB

In [7]:
hfi = hfi.drop(columns=['Short Selling']) #this column has some NaN values do we will remove it.

In [8]:
hfi.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 294 entries, 1997-01-31 to 2021-06-30
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Convertible Arbitrage   294 non-null    object
 1   CTA Global              294 non-null    object
 2   Distressed Securities   294 non-null    object
 3   Emerging Markets        294 non-null    object
 4   Equity Market Neutral   294 non-null    object
 5   Event Driven            294 non-null    object
 6   Fixed Income Arbitrage  294 non-null    object
 7   Global Macro            294 non-null    object
 8   Long/Short Equity       294 non-null    object
 9   Merger Arbitrage        294 non-null    object
 10  Relative Value          294 non-null    object
 11  Funds Of Funds          294 non-null    object
dtypes: object(12)
memory usage: 29.9+ KB

In [11]:
# Function to remove '%' and convert to float
def remove_percent_and_convert(x):
    return float(x.rstrip('%'))

In [12]:
# Apply the function to all elements in the DataFrame
hfi = hfi.applymap(remove_percent_and_convert)

In [13]:
hfi.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 294 entries, 1997-01-31 to 2021-06-30
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Convertible Arbitrage   294 non-null    float64
 1   CTA Global              294 non-null    float64
 2   Distressed Securities   294 non-null    float64
 3   Emerging Markets        294 non-null    float64
 4   Equity Market Neutral   294 non-null    float64
 5   Event Driven            294 non-null    float64
 6   Fixed Income Arbitrage  294 non-null    float64
 7   Global Macro            294 non-null    float64
 8   Long/Short Equity       294 non-null    float64
 9   Merger Arbitrage        294 non-null    float64
 10  Relative Value          294 non-null    float64
 11  Funds Of Funds          294 non-null    float64
dtypes: float64(12)
memory usage: 29.9 KB

In [14]:
hfi = hfi/100
hfi.index = hfi.index.to_period('M')

In [15]:
hfi.head()

,Convertible Arbitrage,CTA Global,Distressed Securities,Emerging Markets,Equity Market Neutral,Event Driven,Fixed Income Arbitrage,Global Macro,Long/Short Equity,Merger Arbitrage,Relative Value,Funds Of Funds
date,,,,,,,,,,,,
1997-01,0.0119,0.0393,0.0178,0.0791,0.0189,0.0213,0.0191,0.0573,0.0281,0.0150,0.0180,0.0317
1997-02,0.0123,0.0298,0.0122,0.0525,0.0101,0.0084,0.0122,0.0175,-0.0006,0.0034,0.0118,0.0106
1997-03,0.0078,-0.0021,-0.0012,-0.0120,0.0016,-0.0023,0.0109,-0.0119,-0.0084,0.0060,0.0010,-0.0077
1997-04,0.0086,-0.0170,0.0030,0.0119,0.0119,-0.0005,0.0130,0.0172,0.0084,-0.0001,0.0122,0.0009
1997-05,0.0156,-0.0015,0.0233,0.0315,0.0189,0.0346,0.0118,0.0108,0.0394,0.0197,0.0173,0.0275